-- 本地开发预创建数据库
CREATE DATABASE IF NOT EXISTS exchange      DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS exchange_dev  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS exchange_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
